Add BloomFilter
engula/engula pull request #12
Opened 2021-09-06 15:46 UTC by ZhongliGao

2021-09-07 02:38 UTC, ZhongliGao commented
close #8

2021-09-07 02:43 UTC, huachaohuang reviewed
Would you please add some comments to explain the algorithm? I don't really understand it at all.

2021-09-07 12:31 UTC, huachaohuang requested changes
Nice try :)

2021-09-07 12:31 UTC, huachaohuang commented on engula/src/format/bloom_filter.rs
> +        let hashers = [
Is that OK to use the same hash function here?

2021-09-07 12:31 UTC, huachaohuang commented on engula/src/format/bloom_filter.rs
> +        (h1.wrapping_add((i).wrapping_mul(h2)) % self.m) as usize
I think LevelDB's implementation is more efficient. Would you like to optimize it?

2021-09-09 03:16 UTC, huachaohuang approved these changes
OK, I can merge it now, but I may refactor it later.

2021-09-09 03:16 UTC, merged