kernel: execute some update operations
engula/engula pull request #273
Opened 2022-01-09 05:00 UTC by huachaohuang

`Kernel` should create/delete the corresponding streams/buckets on receiving updates. The atomicity is not guaranteed so far.

2022-01-09 05:01 UTC, huachaohuang commented
/cc @tisonkun

2022-01-09 06:25 UTC, tisonkun requested changes
I'd prefer make use of the existing `UpdateReader` instead of pollute `UpdateWriter` interface.

See also https://github.com/huachaohuang/engula/pull/4 while async rust is hard to be scoped :-(

2022-01-09 06:33 UTC, tisonkun commented on src/kernel/src/local/update_writer.rs
>          let sequence = self.sequence.fetch_add(1, Ordering::SeqCst) + 1;
Will this event still go through the channel so that the engine receive them? Why does the engine want to receive these events if so?

What if the kernel expose method just create/delete stream/bucket?

The responsibility of UpdateWriter is unclear if it severs blocking create/delete operations.

2022-01-09 06:50 UTC, huachaohuang commented
Oh, these things really don't work that way. It requires a deep understanding of RocksDB internals (and database architecture, perhaps) to understand why `Kernel` exists and how it should work. I don't think I can explain it in simple terms. The best way for me is to show it in the luna engine. And the best way for others is to learn more RocksDB internals.

2022-01-09 07:01 UTC, tisonkun commented
@huachaohuang OK. Go ahead if you're confident is the right direction.

2022-01-09 09:03 UTC, tisonkun commented
@huachaohuang I notice that the `Kernel` can still provide create/delete stream/bucket methods and send the update to the channel internally. To avoid users barely send such an update via `UpdateWriter`, the `KernelUpdate` message should be sealed when exposed.

Anyway, it's an internal optimization. We can revisit the implementation with a basically usable luna-engine or I'll dig into it later.

2022-01-10 06:25 UTC, w41ter-l approved these changes

2022-01-10 06:54 UTC, tisonkun approved these changes
No blocker.

2022-01-10 09:44 UTC, merged