framework/microunit: add some basic structs
engula/engula pull request #64
Opened 2021-11-03 08:40 UTC by huachaohuang

Wow, we have a runnable binary with this PR :)

```
USAGE:
    engula node start <ADDR>
```

2021-11-03 15:06 UTC, tisonkun commented on src/engula-framework/microunit/src/node_server.rs
> +    pub fn serve(&self, _node: Node) {}
Aha. Dummy implementation.

2021-11-03 15:19 UTC, PsiACE commented on src/engula-framework/Cargo.toml
> +microunit = { path = "microunit" }
It seems that two modules should be avoided to depend on each other

2021-11-04 02:33 UTC, tisonkun requested changes
Can we try to adopt a two level ident package structure and let microunit stay at `src/microunit`?

From https://github.com/engula/engula/pull/62#discussion_r742488203 I found it's hard to distinguish engula (the storage engine) and microunit (which should be unaware of the storage engine logic) if microunit stays at `src/engula-framework/microunit` which leads to an imagine microunit being part of engula.

Also `engula-` prefix seems redundant. You can take [materialize](https://github.com/MaterializeInc/materialize/tree/main/src) as an example.

2021-11-04 03:43 UTC, huachaohuang commented
> Can we try to adopt a two level ident package structure and let microunit stay at `src/microunit`?
> 
> From [#62 (comment)](https://github.com/engula/engula/pull/62#discussion_r742488203) I found it's hard to distinguish engula (the storage engine) and microunit (which should be unaware of the storage engine logic) if microunit stays at `src/engula-framework/microunit` which leads to an imagine microunit being part of engula.

So from the perspective of Engula, microunit is part of it, no matter whether microunit is in another crate or repository. However, inside the microunit, it is a standalone crate that can be published alone or moved to another repository.

> 
> Also `engula-` prefix seems redundant. You can take [materialize](https://github.com/MaterializeInc/materialize/tree/main/src) as an example.

A big difference between Engula and other projects like Materialize is that Engula is more a library than a binary. Materialize doesn't need to care about the name of internal crates because those crates are not going to be published. But for Engula, we may want to publish the top-level crates (`engula-xxx` crates) and keep second-level crates internal and unpublished.

2021-11-04 03:49 UTC, huachaohuang commented
> A big difference between Engula and other projects like Materialize is that Engula is more a library than a binary. Materialize doesn't need to care about the name of internal crates because those crates are not going to be published. But for Engula, we may want to publish the top-level crates (`engula-xxx` crates) and keep second-level crates internal and unpublished.

Another alternative is to keep only one top-level crate `engula` and make all other crates internal. This alternative is simpler although users have to compile all features of Engula together. Yet another trick we can do is to use conditional compilation with [feature flags](https://doc.rust-lang.org/cargo/reference/features.html).

2021-11-04 04:04 UTC, tisonkun commented
@huachaohuang thanks for your explanation. Let me think once more about publishing.

2021-11-04 04:05 UTC, huachaohuang commented
Let's move the project layout discussion to https://github.com/engula/engula/issues/59. I think the alternative is worth a try if you think it's easier to understand.

2021-11-04 04:06 UTC, tisonkun approved these changes
LGTM. Postpone layout discussion to #59 .

2021-11-04 15:39 UTC, merged